#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <sys/types.h>
#include <stdbool.h>
#include <unistd.h>

/* General definitions */
# define DELIVERWORK 1
# define GOHOME      0

/**
 *  \brief Main function.
 *
 *  Instantiation of the processing configuration.
 *
 *  \param argc number of words of the command line
 *  \param argv list of words of the command line
 *
 *  \return status of operation
 */
int main (int argc, char *argv[])
{
    MPI_Comm presentComm, nextComm;
    MPI_Group presentGroup, nextGroup;
    int rank, nProc, nProcNow;
    int *sendData = NULL, *recData;
    int gMemb[8];

    MPI_Init (&argc, &argv);
    MPI_Comm_rank (MPI_COMM_WORLD, &rank);
    MPI_Comm_size (MPI_COMM_WORLD, &nProc);
    if (nProc > 8)
      { 
        if (rank == 0) 
            printf ("Too many processes! It should be a power of 2, less or equal to 8.\n");
        MPI_Finalize ();
        return EXIT_FAILURE;
      }
    recData = malloc (length * sizeof (int));
    if (rank == 0)
        { 
            sendData = malloc (length * sizeof (int));
            printf ("Data to be scattered is being generated by process %d.\n", rank);
            for (i = 0; i < length; i++)
            sendData[i] = i;
        }
    nProcNow = nProc;
    presentComm = MPI_COMM_WORLD;
    MPI_Comm_group (presentComm, &presentGroup);
    for (i = 0; i < 8; i++)
     gMemb[i] = i;
}