#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int main (int argc, char *argv[])
{
    int rank, size, i;
    int val, maxVal = -1;
    int *sendData = NULL, *recData;
    int numbers = 64, subSize = 0, extraNumb = 0;

    MPI_Init (&argc, &argv);

    MPI_Comm_rank (MPI_COMM_WORLD, &rank);
    MPI_Comm_size (MPI_COMM_WORLD, &size);
    if (numbers % size == 0)
    {
        subSize = numbers/size;
    } else 
    {
        while(numbers % size != 0)
        {
            numbers++;
            extraNumb++;
        }
        subSize = numbers/size;
    }
    
    recData = malloc (subSize * sizeof (int));

    if (rank == 0)
    {
        printf("n:%d\n",numbers);
        printf("extra:%d\n",extraNumb);
        sendData = malloc (subSize * size * sizeof (int));
        printf ("Data to be scattered\n");
        srandom (getpid ());
        for (i = 0; i < subSize * size; i++)
        {
            val = ((double) rand () / RAND_MAX) * 1000;
            sendData[i] = val;
            printf("%d ", sendData[i]);
        }
        printf("\n");
    }
    MPI_Scatter (sendData, subSize, MPI_INT, recData, subSize, MPI_INT, 0, MPI_COMM_WORLD);
    printf("Received data by process %d: ", rank);
    for (i = 0; i < subSize; i++)
        printf("%2d ", recData[i]);
    printf("\n");
    //printf("Value generated by process %d = %d \n", rank, val);

    
    MPI_Reduce (&recData, &maxVal, subSize, MPI_INT, MPI_MAX, 0, MPI_COMM_WORLD);
    //MPI_Reduce (&val, &minVal, 1, MPI_INT, MPI_MIN, 0, MPI_COMM_WORLD);
    if (rank == 0){
        printf ("Largest value = %d\n", maxVal);
        //printf ("Smallest value = %d\n", minVal);
    };
    
    MPI_Finalize ();
    return EXIT_SUCCESS;
}